apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.env.local.SMTP_PASSWORD }}
  smtp-password: {{ .Values.env.local.SMTP_PASSWORD | b64enc }}
  {{- end }}
  {{- if .Values.env.local.MG_PASSWORD }}
  mailgun-password: {{ .Values.env.local.MG_PASSWORD | b64enc }}
  {{- end }}
