# File for noice errors generation

Name = "mt-errors"
SID = 7

# errors
[[error]]
    Name = "ErrAdminRequired"
    StatusHTTP = 403
    Message = "Admin access required"
    Comment = "User is not admin and has no permissions"
    Kind = 1

[[error]]
    Name = "ErrPermissionsError"
    StatusHTTP = 403
    Message = "Unable to verify permissions"
    Comment = "Unable to verify if user has required permissions, so don't give access"
    Kind = 2

[[error]]
    Name = "ErrRequiredHeadersNotProvided"
    StatusHTTP = 400
    Message = "Required headers not provided"
    Comment = "Required headers is not found in context"
    Kind = 3

[[error]]
    Name = "ErrRequestValidationFailed"
    StatusHTTP = 400
    Message = "Request validation failed"
    Comment = "Validation error when parsing request"
    Kind = 4

#templates errors
[[error]]
    Name = "ErrUnableGetTemplatesList"
    StatusHTTP = 500
    Message = "Unable to get templates list"
    Kind = 5

[[error]]
    Name = "ErrUnableGetTemplate"
    StatusHTTP = 500
    Message = "Unable to get template"
    Kind = 6

[[error]]
    Name = "ErrUnableSaveTemplate"
    StatusHTTP = 500
    Message = "Unable to save template"
    Kind = 7

[[error]]
    Name = "ErrUnableUpdateTemplate"
    StatusHTTP = 500
    Message = "Unable to update template"
    Kind = 8

[[error]]
    Name = "ErrUnableDeleteTemplate"
    StatusHTTP = 500
    Message = "Unable to delete template"
    Kind = 9

[[error]]
    Name = "ErrTemplateAlreadyExists"
    StatusHTTP = 409
    Message = "Template with this name already exists"
    Kind = 10

[[error]]
    Name = "ErrTemplateNotExist"
    StatusHTTP = 404
    Message = "Template with this name doesn't exist"
    Kind = 11

[[error]]
    Name = "ErrTemplateVersionNotExist"
    StatusHTTP = 404
    Message = "Template with this name and version doesn't exist"
    Kind = 12

#messages errors
[[error]]
    Name = "ErrUnableGetMessagesList"
    StatusHTTP = 500
    Message = "Unable to get messages list"
    Kind = 13

[[error]]
    Name = "ErrUnableGetMessage"
    StatusHTTP = 500
    Message = "Unable to get message"
    Kind = 14

[[error]]
    Name = "ErrUnableSaveMessage"
    StatusHTTP = 500
    Message = "Unable to save message"
    Kind = 15

[[error]]
    Name = "ErrMessageNotExist"
    StatusHTTP = 404
    Message = "Message with this name doesn't exist"
    Kind = 16

#mails errors
[[error]]
    Name = "ErrMailSendFailed"
    StatusHTTP = 500
    Message = "Unable to send email"
    Kind = 17

[[error]]
    Name = "ErrInternalError"
    StatusHTTP = 500
    Message = "Internal error"
    Kind = 18