[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/kube-client"

[[constraint]]
  branch = "master"
  name = "git.containerum.net/ch/json-types"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "v1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/contrib"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/google/uuid"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "gopkg.in/mailgun/mailgun-go.v1"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "1.0.0"