
[[constraint]]
  branch = "master"
  name = "git.containerum.net/ch/utils"

[[constraint]]
  branch = "master"
  name = "github.com/blang/semver"

[[constraint]]
  branch = "master"
  name = "github.com/boltdb/bolt"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/contrib"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/gin"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.4"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/smartystreets/goconvey"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "gopkg.in/mailgun/mailgun-go.v1"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "git.containerum.net/ch/json-types"