[prune]
    go-tests = true
    unused-packages = true
    non-go = true

  [[prune.project]]
    name = "github.com/containerum/utils"
    non-go = false

  [[prune.project]]
    name = "github.com/containerum/cherry"
    non-go = false

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "v1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/contrib"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.2"

[[constraint]]
  branch = "master"
  name = "github.com/google/uuid"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "gopkg.in/mailgun/mailgun-go.v1"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "1.6"

[[constraint]]
  version = "^v1.0.1-rc2"
  name = "github.com/containerum/cherry"

[[constraint]]
  name = "github.com/containerum/utils"
  version = "^1.0.0"