swagger: "3.0"
parameters:
  UserRoleHeader:
    $ref: "vendor/github.com/containerum/utils/httputil/swagger.json#/parameters/UserRoleHeader"
responses:
  error:
    description: cherry error
    schema:
      $ref: "vendor/github.com/containerum/cherry/swagger.json#/definitions/Err"
