replicaCount: 1

image:
  repository: containerum/mail
  tag: v1.0.0
  pullPolicy: Always

service:
  port: 7070
  targetPort: 7070
  externalIP:

volumeMounts:
  name: mail-volume
  mountPath: "/storage"

volume:
  name: mail-volume
  empty:
    emptyDir: {}
  gluster:
    glusterfs:
      endpoints: glusterfs
      path: sys_gv_hosting_mail_templater_data

env:
  GIN_MODE: debug
  CH_MAIL_LOG_LEVEL: 4
  CH_MAIL_TEMPLATE_DB: "../../storage/template.db"
  CH_MAIL_MESSAGES_DB: "../../storage/messages.db"
  CH_MAIL_UPSTREAM: "mailgun"
  CH_MAIL_UPSTREAM_SIMPLE: "smtp"
  CH_MAIL_SENDER_NAME_SIMPLE: "containerum"
  CH_MAIL_SENDER_MAIL_SIMPLE: "noreply-test@containerum.io"
  CH_MAIL_SENDER_NAME: "containerum"
  CH_MAIL_SENDER_MAIL: "noreply-test@containerum.io"
  CH_MAIL_USER_MANAGER_URL: "http://user-manager:8111"
  CH_MAIL_LISTEN_ADDR: ":7070"
  CH_MAIL_SMTP_ADDR: "mail:465"
  CH_MAIL_SMTP_LOGIN: "noreply-test@containerum.io"
  CH_MAIL_SMTP_PASSWORD: "pass"
